name: Build and deploy Node.js app to Azure Web App - CLSGCounsellorPanel

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: bookings # Matches your project structure

      - name: Debug directory structure
        run: |
          pwd
          ls -R

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build the app
        run: |
          cd bookings/admin # Adjust to where `package.json` exists
          npm install
          npm run build
        working-directory: ./bookings/admin

      - name: Include index.html and web.config in artifact
        run: |
          mkdir -p ./bookings/admin/dist
          echo "Copying index.html and web.config"
          cp ./bookings/admin/index.html ./bookings/admin/dist/
          cp ./bookings/admin/web.config ./bookings/admin/dist/
          ls -R ./bookings/admin/dist

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./bookings/admin/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for requesting the JWT

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Debug downloaded artifact
        run: |
          pwd
          ls -R

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E04FD9C42C9445689B0FB60B08F14F48 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A0C33C26F9994F88A0B1D09690B8DF43 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_11E868E4D5CE4BDB8E7D87A69DFA5E88 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'CLSGCounsellorPanel'
          package: ./bookings/admin/dist


