name: Build and deploy Node.js app to Azure Web App - CLSGCounsellorBookings

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Force delete .env
        run: |
          cd ./frontend/build
          chmod +w .env 2>/dev/null || true  # Make writable if needed
          rm -f .env
          ls -la  # Confirm deletion

      - name: Verify build output
        run: |
          cd frontend/build
          ls -la

      - name: Create .env file for Vite
        env:
           FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
           VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
           VITE: vite
        run: |
          cd frontend/build
          touch .env
          echo "VITE_FRONTEND_URL=${FRONTEND_URL}" >> .env
          echo "VITE=${VITE}" >> .env
          echo "VITE_BACKEND_URL=${VITE_BACKEND_URL}" >> .env
          echo ".env file created with VITE-prefixed variables"
          ls -la  # Verify .env file creation

      - name: npm install, build, and test
        run: |
          cd frontend
          npm install
          npm run build 
          npm test --if-present 
          
      - name: Ensure .env is in the deployment package
        run: |
          cd frontend/build
          if [ -f .env ]; then
            echo ".env file exists and is ready for deployment"
          else
            echo "Error: .env file not found"
            exit 1
          fi
      
      - name: Verify final artifact structure
        run: |
          ls -R ./frontend/build
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            ./frontend/build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

    #  - name: Verify .env file in deployment package
      #  run: |
      #    cd frontend/build
      #    if [ -f .env ]; then
      #      echo ".env file exists in deployment package"
      #      cat .env  # Display contents for verification
      #    else
      #      echo "Error: .env file not found in deployment package"
       #     exit 1
    #      fi

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'CLSGCounsellorBookings'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
