# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - CLSGCounsellorBookings

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # Use Ubuntu instead of Windows

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x' # Use Node.js 20.x

      - name: Clean old build files
        run: |
          cd frontend
          rm -rf   .env  # 


  
      - name: Create .env file for Vite
        env:
           FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
           VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
        run: |
          cd frontend
          rm -f .env  # Delete the old .env file if it exists
          touch .env  # Create a new .env file
          echo "VITE_FRONTEND_URL=${FRONTEND_URL}" >> .env
          echo "VITE_BACKEND_URL=${VITE_BACKEND_URL}" >> .env
          echo ".env file created with VITE-prefixed variables"

      - name: npm install, build, and test
        run: |
          cd frontend
          npm install
          npm run build 
          npm test --if-present 
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            ./frontend/build
            ./frontend/build/.env
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'CLSGCounsellorBookings'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
