name: Build and deploy Node.js app to Azure Web App - bookingsfront

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: bookings

      - name: Debug directory structure
        run: |
          pwd
          ls -R

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build
        run: |
          cd bookings/frontend
          echo "VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }}" > .env
          npm install
          npm run build
          npm test --if-present

      - name: Add staticwebapp.config.json
        run: |
          cat <<EOT > bookings/frontend/build/staticwebapp.config.json
          {
            "routes": [
              {
                "route": "/",
                "rewrite": "/index.html"
              },
              {
                "route": "/counsellors",
                "rewrite": "/index.html"
              },
              {
                "route": "/counsellors/:speciality",
                "rewrite": "/index.html"
              },
              {
                "route": "/about",
                "rewrite": "/index.html"
              },
              {
                "route": "/contact",
                "rewrite": "/index.html"
              },
              {
                "route": "/my-profile",
                "rewrite": "/index.html"
              },
              {
                "route": "/my-appointments",
                "rewrite": "/index.html"
              },
              {
                "route": "/appointment/:docId",
                "rewrite": "/index.html"
              },
              {
                "route": "/login",
                "rewrite": "/index.html"
              },
              {
                "route": "/forgot-password",
                "rewrite": "/index.html"
              },
              {
                "route": "/password-reset/:id/:token",
                "rewrite": "/index.html"
              },
              {
                "route": "/api/*",
                "allowedRoles": ["authenticated"]
              }
            ],
            "navigationFallback": {
              "rewrite": "/index.html",
              "exclude": ["/api/*"]
            }
          }
          EOT

      - name: Verify modified files
        run: |
          cd bookings/frontend/build
          ls -lah
          find . -type f -exec sha256sum {} \;

      - name: Zip the build folder
        run: |
          cd bookings/frontend
          zip -r build.zip build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: bookings/frontend/build.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip build.zip -d build

      - name: Debug build folder
        run: |
          cd build
          ls -lah

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A4D65CCC9686424884BAD17614DBC8C0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D023D18A0492409D884C74A202791ACA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F578E15C12644C0C8ED7B0DC0F3B3C0F }}

      - name: Restart Azure Web App
        run: |
          az webapp restart --name clsgbookingsfront --resource-group CitySchools_Bookings_System

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'clsgbookingsfront'
          slot-name: 'Production'
          package: ./build
