name: Build and deploy Node.js app to Azure Web App - bookingsfront

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: bookings

      - name: Debug directory structure
        run: |
          pwd
          ls -R

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          cd bookings/frontend
          echo "VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }}" > .env
          npm install
          npm run build
          npm test --if-present

      - name: Verify final artifact structure
        run: |
          ls -R ./bookings/frontend/build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./bookings/frontend/build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Debug downloaded artifact
        run: |
          pwd
          ls -R

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A4D65CCC9686424884BAD17614DBC8C0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D023D18A0492409D884C74A202791ACA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F578E15C12644C0C8ED7B0DC0F3B3C0F }}

      - name: Clear Azure Web App cache
        run: |
          az webapp config appsettings set --name clsgbookingsfront --resource-group CitySchools_Bookings_System --settings WEBSITE_LOCAL_CACHE_OPTION=Never
          az webapp restart --name clsgbookingsfront --resource-group CitySchools_Bookings_System

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'clsgbookingsfront'
          slot-name: 'Production'
          package: ./
