

name: Build and deploy Node.js app to Azure Web App - CLSGCounsellorsPanel

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: bookings # Matches your project structure

      - name: Debug directory structure
        run: |
          pwd
          ls -R

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          cd bookings/admin # Adjust to where `package.json` exists
          npm install
          npm run build 
          npm test --if-present 

      - name: Prepare artifact with dependencies
        run: |
          cp ./bookings/admin/package.json ./bookings/admin/dist 
          cd ./bookings/admin/dist
          npm install --omit=dev # Ensure runtime dependencies

      - name: Verify final artifact structure
        run: |
          ls -R ./bookings/admin/dist

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./bookings/admin/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Debug downloaded artifact
        run: |
          pwd
          ls -R

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FB0156AE123F4678A31EEA4BC9452F01 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A3EA067A15DE473BB7222A94CC5FC7AD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FB0709E95E364E6DBA52F37D2307817D }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'CLSGCounsellorsPanel'
          package: ./



          
