name: Build and deploy Node.js app to Azure Web App - clsgbookingsdb

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Create and validate .env file
      - name: Create and validate .env file
        env:
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          CLOUDINARY_NAME: ${{ secrets.CLOUDINARY_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_SECRET_KEY: ${{ secrets.CLOUDINARY_SECRET_KEY }}
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          HOST: ${{ secrets.HOST }}
          SERVICE: ${{ secrets.SERVICE }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          SECURE: ${{ secrets.SECURE }}
          USER: ${{ secrets.USER }}
          PASS: ${{ secrets.PASS }}
          FRONTEND_URLC: ${{ secrets.FRONTEND_URLC }}
        run: |
          cd backend
          echo "Creating .env file..."
          cat <<EOF > .env
          FRONTEND_URL=${FRONTEND_URL}
          FRONTEND_URLC=${FRONTEND_URLC}
          PASS=${PASS}
          USER=${USER}
          SECURE=${SECURE}
          EMAIL_PORT=${EMAIL_PORT}
          SERVICE=${SERVICE}
          HOST=${HOST}
          JWT_SECRET=${JWT_SECRET}
          ADMIN_PASSWORD=${ADMIN_PASSWORD}
          ADMIN_EMAIL=${ADMIN_EMAIL}
          CLOUDINARY_SECRET_KEY=${CLOUDINARY_SECRET_KEY}
          CLOUDINARY_NAME=${CLOUDINARY_NAME}
          MONGODB_URI=${MONGODB_URI}
          EOF
          echo ".env file created and validated."

      # Install dependencies
      - name: Install Node.js dependencies
        run: |
          cd backend
          npm install

      # Verify the start script in package.json
      - name: Verify start script
        run: |
          cd backend
          echo "Verifying start script in package.json..."
          cat package.json | grep '"start":'

      # Prepare deployment artifact
      - name: Create deployment artifact
        run: |
          cd backend
          zip -r node-app.zip .

      # Debug deployment artifact creation
      - name: Debug deployment artifact
        run: |
          cd backend
          echo "Inspecting deployment artifact..."
          ls -la
          file node-app.zip

      # Upload the deployment artifact for use in the next job
      - name: Upload deployment artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: backend/node-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Download the artifact from the build job
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # Verify the downloaded artifact content
      - name: Verify artifact content
        run: |
          echo "Verifying downloaded artifact content..."
          ls -la
          unzip -l node-app.zip

      # Authenticate with Azure using the Publish Profile
      - name: Azure Login
        uses: azure/login@v1
        with:
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILEDB }}

      # Set Azure App Service Startup Command using Azure CLI
      - name: Set Azure App Service Startup Command
        run: |
          echo "Setting Azure App Service configuration..."
          az webapp config appsettings set \
            --resource-group CitySchools_Bookings_System \
            --name CLSGBookingsDB \
            --settings WEBSITES_PORT=4000 SCM_DO_BUILD_DURING_DEPLOYMENT=true
          az webapp config set \
            --resource-group CitySchools_Bookings_System \
            --name CLSGBookingsDB \
            --startup-file "npm start"

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CLSGBookingsDB'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILEDB }}
          package: ./node-app.zip
